In [142]:
import pandas, os
data_base_path = os.path.join(os.path.dirname(os.getcwd()), "data_base", "data_base.csv")
df = pandas.read_csv(data_base_path)
df

,post_id,post_title,parser_time,like-count,comment_count,collection,share_count
0,7342330193819847937,🐱：我是全世界最乖的貓貓了｜感謝 _lyy_0610 授權｜#即新聞 #橘貓 #搞笑 #寵物...,2024-03-11 16,2917,30.0,273.0,224.0
1,7342330447336099073,當你開車屎在滾｜感謝 IG achia0、Vcaotun_taiwan 授權｜#即新聞 #夫...,2024-03-11 16,163,5.0,10.0,31.0
2,7342330890653027585,說好的女兒都是小棉襖呢🤣｜感謝 IG addchi_ 授權｜#即新聞 #母女 #女兒 #小朋...,2024-03-11 16,88,1.0,3.0,1.0
3,7342331196728462594,黑面琵鷺的台語我還真的第一次聽說｜感謝 珊迪傑 I'm Sandy 授權｜#即新聞 #台語 ...,2024-03-11 16,393,0.0,49.0,18.0
4,7342331608764026114,🐶：不幫我撿就算了，你還搞事情？？？｜感謝 IG fav_1212 授權｜#即新聞 #柯基 ...,2024-03-11 16,304,0.0,17.0,21.0
...,...,...,...,...,...,...,...
3673,7345827242691382546,日本SpaceOne火箭首飛失敗 升空數秒就爆炸了 #即新聞 #火箭 #爆炸,2024-03-14 19,118,5.0,1.0,2
3674,7346028710543314178,絕對要看到最後！警察臨檢抓通緝，劇情一個反轉 #即新聞 #警察 #通緝,2024-03-14 19,4997,98.0,371.0,332
3675,7346035862842494209,老婆這番話也太有道理🤣｜感謝 IG assists_seed 授權｜#即新聞 #夫妻 #夫妻...,2024-03-14 19,94,3.0,3.0,10
3676,7346036312337599746,貓咪完美示範逃跟飛一樣｜感謝 IG bai_lu_s 授權｜#即新聞 #貓咪 #貓,2024-03-14 19,109,0.0,3.0,3
3677,7346036564461374722,小哥哥哄弟弟那段整個失去靈魂啊🤣｜感謝 IG jay1102 授權｜#即新聞 #小朋友 #小...,2024-03-14 19,117,0.0,3.0,4

# Pandas map solve

In [143]:
import numpy
def k_unit_translate(var) : 
    try : 
        if "K" in var : 
            var = float(var.split("K")[0])*1000
            return var
        else : 
            return var
    except : 
        return var

def text_in_var(var) : 
    try : 
        var = float(var)
        return var
    except : 
        var = numpy.nan
        return var
        
var_list = ["like-count", "comment_count", "collection", "share_count"]
for var in var_list : 
    df[var] = df[var].map(k_unit_translate)
    df[var] = df[var].map(text_in_var)

# Parser_time solve

In [144]:
# 爬取時間檢查
df['parser_time'] = pandas.to_datetime(df['parser_time'])
print(f"爬取開始時間為 : {df['parser_time'].min()}")
print(f"爬取終止時間為 : {df['parser_time'].max()}")

爬取開始時間為 : 2024-03-11 16:00:00
爬取終止時間為 : 2024-03-14 19:00:00

# None solve

In [145]:
# 檢查遺漏值
missing_df = df[df.isnull().any(axis=1)]
missing_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175 entries, 32 to 3654
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   post_id        175 non-null    int64
 1   post_title     4 non-null      object
 2   parser_time    175 non-null    datetime64[ns]
 3   like-count     5 non-null      float64
 4   comment_count  5 non-null      float64
 5   collection     5 non-null      float64
 6   share_count    1 non-null      float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 10.9+ KB

In [146]:
missing_df["post_id"].unique()

array([7343831263322705154, 7343097239033695490, 7344919339377904897,
       7342330193819847937, 7343803915080715521, 7342720927987289362,
       7342343451909901569, 7343550823487573253, 7345044431491353857,
       7342330890653027585, 7342331196728462594, 7345422226205740290,
       7345421893308026114, 7344919085953699073, 7343097421099961602,
       7342331608764026114, 7343169767081020673, 7344919610401082626,
       7344993886437215495, 7343800866626882834], dtype=int64)

## 類型一 : parser 缺漏
<img src="picture\7343097239033695490.png" alt="替代文字" width=600 height=375>

In [147]:
missing_df[missing_df["post_id"] == 7342330890653027585]

,post_id,post_title,parser_time,like-count,comment_count,collection,share_count
1340,7342330890653027585,NaN,2024-03-13,NaN,NaN,NaN,NaN

## 類型二 : title 欄位缺漏
<img src="picture\7342330193819847937_1.png" alt="替代文字" width=800 height=100><br>
<img src="picture\7342330193819847937_2.png" alt="替代文字" width=1100 height=500>

In [148]:
missing_df[missing_df["post_id"] == 7342330193819847937]

,post_id,post_title,parser_time,like-count,comment_count,collection,share_count
111,7342330193819847937,NaN,2024-03-11 19:00:00,2978.0,31.0,277.0,231.0

In [149]:
# 根據未遺失 title 的資料，填埔缺失的貼文資訊
print(f"填補前具有遺漏值的貼文量 : {len(missing_df['post_id'].unique())}")
for missing_post in missing_df["post_id"].unique() : 
    try : 
        missing_post_title = df[(df["post_id"] == missing_post) & (df["post_title"].notna())]["post_title"].values[0]
        df.loc[df["post_id"] == missing_post, "post_title"] = missing_post_title
    except : 
        pass

missing_df = df[df.isnull().any(axis=1)]
print(f"填補後具有遺漏值的貼文量 : {len(missing_df['post_id'].unique())}")

填補前具有遺漏值的貼文量 : 20
填補後具有遺漏值的貼文量 : 19

## 類型三 : 文章遭到刪除
<img src="picture\7344919339377904897.png" alt="替代文字" width=600 height=375>

In [150]:
missing_df[missing_df["post_id"] == 7344919339377904897]

,post_id,post_title,parser_time,like-count,comment_count,collection,share_count
108,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-11 18:00:00,NaN,NaN,NaN,NaN
146,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-11 19:00:00,NaN,NaN,NaN,NaN
185,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-11 20:00:00,NaN,NaN,NaN,NaN
225,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-11 21:00:00,NaN,NaN,NaN,NaN
265,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-11 22:00:00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
3420,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-14 15:00:00,NaN,NaN,NaN,NaN
3478,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-14 16:00:00,NaN,NaN,NaN,NaN
3536,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-14 17:00:00,NaN,NaN,NaN,NaN
3595,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-14 18:00:00,NaN,NaN,NaN,NaN
3654,7344919339377904897,又是一位合法最強小三🤣｜感謝 IG yuhan0710 授權｜#即新聞 #女兒 #親子 #母...,2024-03-14 19:00:00,NaN,NaN,NaN,NaN

# line plot output

In [151]:
df

,post_id,post_title,parser_time,like-count,comment_count,collection,share_count
0,7342330193819847937,🐱：我是全世界最乖的貓貓了｜感謝 _lyy_0610 授權｜#即新聞 #橘貓 #搞笑 #寵物...,2024-03-11 16:00:00,2917.0,30.0,273.0,224.0
1,7342330447336099073,當你開車屎在滾｜感謝 IG achia0、Vcaotun_taiwan 授權｜#即新聞 #夫...,2024-03-11 16:00:00,163.0,5.0,10.0,31.0
2,7342330890653027585,說好的女兒都是小棉襖呢🤣｜感謝 IG addchi_ 授權｜#即新聞 #母女 #女兒 #小朋...,2024-03-11 16:00:00,88.0,1.0,3.0,1.0
3,7342331196728462594,黑面琵鷺的台語我還真的第一次聽說｜感謝 珊迪傑 I'm Sandy 授權｜#即新聞 #台語 ...,2024-03-11 16:00:00,393.0,0.0,49.0,18.0
4,7342331608764026114,🐶：不幫我撿就算了，你還搞事情？？？｜感謝 IG fav_1212 授權｜#即新聞 #柯基 ...,2024-03-11 16:00:00,304.0,0.0,17.0,21.0
...,...,...,...,...,...,...,...
3673,7345827242691382546,日本SpaceOne火箭首飛失敗 升空數秒就爆炸了 #即新聞 #火箭 #爆炸,2024-03-14 19:00:00,118.0,5.0,1.0,2.0
3674,7346028710543314178,絕對要看到最後！警察臨檢抓通緝，劇情一個反轉 #即新聞 #警察 #通緝,2024-03-14 19:00:00,4997.0,98.0,371.0,332.0
3675,7346035862842494209,老婆這番話也太有道理🤣｜感謝 IG assists_seed 授權｜#即新聞 #夫妻 #夫妻...,2024-03-14 19:00:00,94.0,3.0,3.0,10.0
3676,7346036312337599746,貓咪完美示範逃跟飛一樣｜感謝 IG bai_lu_s 授權｜#即新聞 #貓咪 #貓,2024-03-14 19:00:00,109.0,0.0,3.0,3.0
3677,7346036564461374722,小哥哥哄弟弟那段整個失去靈魂啊🤣｜感謝 IG jay1102 授權｜#即新聞 #小朋友 #小...,2024-03-14 19:00:00,117.0,0.0,3.0,4.0

In [152]:
from matplotlib.font_manager import FontProperties
import matplotlib.pyplot as plt
import numpy
import warnings
import pandas
import traceback
import os

# 設置中文字體路徑
font_path = 'ttf\SimHei.ttf'
myfont = FontProperties(fname=r'ttf\chinese.simhei.ttf')

# 關閉因 emoji 無法正常顯示在標題的警告
warnings.filterwarnings("ignore", message="Glyph .* missing from current font")

# set plot-var-list
plot_var_list = ["like-count", "comment_count", "collection", "share_count"]

error_info_list = []
for post_id in df["post_id"].unique() : 
    for plot_var in plot_var_list : 
        try :
            post_df = df[df["post_id"] == post_id].copy() 
            if len(post_df[post_df["post_title"].notna()]["post_title"].values) == 0 : # title field may not necessarily have a value.
                continue
            
            post_df[plot_var] = post_df[plot_var].astype(float)
            plot_title = post_df[post_df["post_title"].notna()]["post_title"].values[0]
            values_axis = post_df[plot_var]
            time_axis = post_df["parser_time"]

            # 繪製折線圖
            plt.plot(time_axis, values_axis, label=plot_var)
            plt.title(plot_title.split("#")[0], fontproperties=myfont)
            plt.xlabel('parser_time', fontproperties=myfont)

            # 額外設定
            time_axis_ticks = pandas.date_range(start=post_df["parser_time"].min(), end = post_df["parser_time"].max(), freq='h')
            time_axis_ticks = time_axis_ticks[::12]
            plt.xticks(time_axis_ticks, [tick.strftime('%m-%d %H') for tick in time_axis_ticks], rotation=45)
            plt.legend()

            # save line-plot
            save_path = os.path.join(os.path.dirname(os.getcwd()), "line_plot", f"{post_id}")
            if not os.path.exists(save_path):
                os.makedirs(save_path)
            
            plt.savefig(os.path.join(save_path, f'{plot_var}.png'), dpi=300)
            plt.close()
        except : 
            error_info = {"post_id" : post_id, "plot_var" : plot_var, "traceback" : traceback.format_exc()}
            error_info_list.append(error_info)
            continue

error_info_df = pandas.DataFrame(error_info_list)
error_info_df.to_json("plot_error.json")

# plot debug

In [153]:
# debug
error_df = pandas.read_json("plot_error.json")
error_df

Empty DataFrame
Columns: []
Index: []